from __future__ import annotations

import shlex
from collections.abc import Iterable

from .diagnostics import Finding
from .models import Manifest


def _code_block_command(manifest: Manifest) -> str:
    command = shlex.join(manifest.command.argv)
    if manifest.command.cwd != ".":
        command = f"cd {shlex.quote(manifest.command.cwd)} && {command}"
    return command


def _source_line(manifest: Manifest) -> str:
    source = manifest.source
    values = []
    if source.repository:
        values.append(f"repository `{source.repository}`")
    if source.commit:
        values.append(f"commit `{source.commit}`")
    if source.branch:
        values.append(f"branch `{source.branch}`")
    return ", ".join(values) if values else "not declared"


def build_issue_body(
    manifest: Manifest,
    findings: Iterable[Finding] = (),
    *,
    bundle_name: str | None = None,
) -> str:
    """Build a safe, metadata-only GitHub issue body from a verified manifest.

    The function intentionally never reads the pack directory. It can therefore
    only expose fields already accepted by the manifest schema, plus privacy
    finding locations and messages (never matched evidence values).
    """
    finding_list = list(findings)
    status = manifest.observed.status
    exit_code = (
        "unknown" if manifest.observed.exit_code is None else str(manifest.observed.exit_code)
    )
    producer = "not declared"
    if manifest.producer:
        producer = manifest.producer.name
        if manifest.producer.version:
            producer += f" {manifest.producer.version}"
        if manifest.producer.runtime:
            producer += f" ({manifest.producer.runtime})"
    lines = [
        "## Failure reproduction report",
        "",
        "> Generated by FaultPack from a verified, privacy-preflighted evidence capsule.",
        "> The report intentionally contains metadata and digests, not captured stdout/stderr.",
        "",
        "### Summary",
        "",
        f"- **Pack fingerprint:** `{manifest.fingerprint or 'not declared'}`",
        f"- **Observed status:** `{status}`",
        f"- **Observed exit code:** `{exit_code}`",
        f"- **Observed duration:** `{manifest.observed.duration_ms} ms`",
        f"- **Producer:** `{producer}`",
        f"- **Source:** {_source_line(manifest)}",
        "",
        "### Reproduction contract",
        "",
        "```sh",
        _code_block_command(manifest),
        "```",
        "",
        f"The command is expected to exit with `{manifest.expectation.exit_code}`.",
    ]
    if manifest.expectation.stdout_regex or manifest.expectation.stderr_regex:
        lines.append(
            "The failure oracle includes declared output patterns; these are omitted from this "
            "issue body to keep the report passive and compact."
        )
    if manifest.input_files:
        lines.extend(["", "### Declared inputs", ""])
        lines.extend(f"- `{entry.path}` — `{entry.sha256}`" for entry in manifest.input_files)
    else:
        lines.extend(["", "### Declared inputs", "", "No input files were declared."])
    if manifest.events:
        lines.extend(["", "### Evidence timeline", ""])
        lines.extend(
            f"- `{event.sequence}` `{event.kind}` — `{event.name}`" for event in manifest.events
        )
    lines.extend(["", "### Privacy preflight", ""])
    if finding_list:
        lines.append(
            f"**Review required:** {len(finding_list)} finding(s) were detected before sharing."
        )
        lines.extend(
            f"- `{item.severity}` `{item.code}` in `{item.path}`"
            + (f" at line {item.line}" if item.line else "")
            + f": {item.message}"
            for item in finding_list
        )
        lines.append(
            "Do not attach the bundle until every finding has been reviewed and, if necessary, "
            "removed or redacted."
        )
    else:
        lines.append(
            "No configured secret or PII indicators were detected in declared textual evidence. "
            "Manual review is still required."
        )
    lines.extend(
        [
            "",
            "### Maintainer checklist",
            "",
            "- [ ] Download the attached FaultPack bundle, if present.",
            "- [ ] Run `faultpack verify` before executing anything.",
            "- [ ] Replay only in an isolated runner with appropriate filesystem and network "
            "restrictions.",
            "- [ ] Compare the reproduction result with the declared oracle.",
        ]
    )
    if bundle_name:
        lines.extend(["", f"**Suggested attachment:** `{bundle_name}`"])
    lines.extend(
        [
            "",
            "<sub>FaultPack verifies integrity but is not a sandbox and does not prove that the "
            "producer's original observation was truthful.</sub>",
            "",
        ]
    )
    return "\n".join(lines)
